### ISSUE TITLE
Custom TFlite Model shows continual white screen

### ISSUE THREAD

**Issue by AJAX6255** [fritzlabs/heartbeat-android#5]
Image Labeling feature, Object detection feature and custom TFmobile Model work, however the 4th feature (custom TFlite model) simply shows a white screen even when detect button is pushed. When button is pushed it gives small text prompt "Not detected". This is an Android Studio 3.3 canary build.
I have not yet looked into the code for feature 4.

**Comment by AJAX6255** [comment]
AAAAH! Now I get it. You are supposed to DRAW the number on the white
portion of the  Screen . YES it detects the handwritten number (not too
accurately). Ha my BAD.
I made the assumption that it was going to OCR it from a camera input.
OK maybe just a bit more descriptive on the models page would help a bunch!

1). Also Image Labeling Feature - does not seem to have anything to do with
Video frames that I can see..... (possibly poor description).

2). A help button would also be great with "about" Fritz, heartbeat, (the
brilliant team) etc.

3). The custom TFmobile model seems very inaccurate and when it does
recognize they are very low percentages of confidence. .2-.4 (should be .8
- .94)

Thanks for your help.

**Comment by hsiaoer** [comment]
Yes we definitely can add a clearer description on the page listing all the models/ features. As for the custom tfmobile model, thanks for pointing out the low confidence. We can try to swap that model out for a better one.

**Comment by abdinoor** [comment]
Thanks for the feedback @AJAX6255. I'm going to close out this issue now. If you want to ask more questions feel free to reach out to us via the email help (at) fritz.ai
